//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public int id_ficha { get; set; }
        public int rut_paciente { get; set; }
        public string dv_paciente { get; set; }
        public string nombre_paciente { get; set; }
        public string apellido_paciente { get; set; }
    }
}
